"""add assignments and reference checks

Revision ID: 131c4f8d89eb
Revises: 7f0302820c71
Create Date: 2026-08-26 10:57:16.023382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131c4f8d89eb'
down_revision: Union[str, Sequence[str], None] = '7f0302820c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_name', sa.String(), nullable=False),
    sa.Column('role_category', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('skills_covered', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('assignment_content', sa.Text(), nullable=True),
    sa.Column('evaluation_criteria', sa.JSON(), nullable=True),
    sa.Column('historical_usage_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('assignment_repository_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('submission_deadline', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('technical_accuracy_score', sa.Float(), nullable=True),
    sa.Column('problem_solving_score', sa.Float(), nullable=True),
    sa.Column('clarity_structure_score', sa.Float(), nullable=True),
    sa.Column('practical_thinking_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('weighted_total', sa.Float(), nullable=True),
    sa.Column('scored_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_repository_id'], ['assignment_repository.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('reference_name', sa.String(), nullable=True),
    sa.Column('reference_relationship', sa.String(), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('overall_outcome', sa.String(), nullable=True),
    sa.Column('positive_signals', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('rehire_eligibility', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('logged_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_checks')
    op.drop_table('assignments')
    op.drop_table('assignment_repository')
    # ### end Alembic commands ###
