"""baseline schema

Revision ID: 7f0302820c71
Revises: 
Create Date: 2026-08-26 10:43:55.459530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0302820c71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('hiring_manager', sa.String(), nullable=False),
    sa.Column('hiring_priority', sa.String(), nullable=False),
    sa.Column('target_joining_date', sa.DateTime(), nullable=True),
    sa.Column('number_of_openings', sa.Integer(), nullable=True),
    sa.Column('replacement_or_new', sa.String(), nullable=True),
    sa.Column('experience_range', sa.String(), nullable=True),
    sa.Column('mandatory_skills', sa.JSON(), nullable=True),
    sa.Column('nice_to_have_skills', sa.JSON(), nullable=True),
    sa.Column('business_need', sa.Text(), nullable=True),
    sa.Column('kpi_expectations', sa.Text(), nullable=True),
    sa.Column('assignment_required', sa.Boolean(), nullable=True),
    sa.Column('suggested_interviewers', sa.JSON(), nullable=True),
    sa.Column('suggested_compensation_range', sa.String(), nullable=True),
    sa.Column('compensation_range', sa.String(), nullable=True),
    sa.Column('offer_strategy_notes', sa.Text(), nullable=True),
    sa.Column('internal_risk_notes', sa.Text(), nullable=True),
    sa.Column('jd', sa.Text(), nullable=True),
    sa.Column('hiring_notes', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('candidate_source', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority_override', sa.String(), nullable=True),
    sa.Column('needs_founder_review', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('stage_from', sa.String(), nullable=True),
    sa.Column('stage_to', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('is_stage_skip', sa.Boolean(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('interviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('interviewer_name', sa.String(), nullable=True),
    sa.Column('evaluation_area', sa.String(), nullable=True),
    sa.Column('coverage_level', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('assessment', sa.String(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('concerns', sa.Text(), nullable=True),
    sa.Column('suggested_future_probes', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_screening_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('recruiter_summary', sa.Text(), nullable=True),
    sa.Column('key_positives', sa.Text(), nullable=True),
    sa.Column('key_concerns', sa.Text(), nullable=True),
    sa.Column('compensation_alignment', sa.Text(), nullable=True),
    sa.Column('notice_period_summary', sa.Text(), nullable=True),
    sa.Column('communication_assessment', sa.Text(), nullable=True),
    sa.Column('motivation_level', sa.String(), nullable=True),
    sa.Column('recruiter_recommendation', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_screening_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('matched_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('suggested_probe_areas', sa.JSON(), nullable=True),
    sa.Column('suggested_priority', sa.String(), nullable=True),
    sa.Column('score_explanation', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_screening_results')
    op.drop_table('recruiter_screening_notes')
    op.drop_table('interviews')
    op.drop_table('activity_timeline')
    op.drop_table('candidates')
    op.drop_table('users')
    op.drop_table('sla_clocks')
    op.drop_table('roles')
    # ### end Alembic commands ###
