"""add pending items: AI contract persistence, remaining SLA stages

Revision ID: a1783edf671a
Revises: 03a97816f6f8
Create Date: 2026-08-27 11:17:36.898391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1783edf671a'
down_revision: Union[str, Sequence[str], None] = '03a97816f6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_checks', sa.Column('ai_model_used', sa.String(), nullable=True))
    op.add_column('resume_screening_results', sa.Column('triggered_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_screening_results', 'triggered_by')
    op.drop_column('reference_checks', 'ai_model_used')
    # ### end Alembic commands ###
