"""add candidate lifecycle: rejection/withdrawal reasons, joining risk tracker

Revision ID: f10c4c0b2283
Revises: fa94448565a7
Create Date: 2026-08-26 13:55:08.381441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10c4c0b2283'
down_revision: Union[str, Sequence[str], None] = 'fa94448565a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joining_risk_trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_owner', sa.String(), nullable=True),
    sa.Column('joining_confidence', sa.String(), nullable=True),
    sa.Column('pending_documents', sa.Text(), nullable=True),
    sa.Column('joining_confirmed', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.add_column('candidates', sa.Column('rejection_reason', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('withdrawal_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'withdrawal_reason')
    op.drop_column('candidates', 'rejection_reason')
    op.drop_table('joining_risk_trackers')
    # ### end Alembic commands ###
