"""add parsing_status to resume screening results

Revision ID: fa94448565a7
Revises: 131c4f8d89eb
Create Date: 2026-08-26 12:22:04.029917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa94448565a7'
down_revision: Union[str, Sequence[str], None] = '131c4f8d89eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_screening_results', sa.Column('parsing_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_screening_results', 'parsing_status')
    # ### end Alembic commands ###
